### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by sdaves** [suned/pfun#103]
When do you plan on a Release for 1.0.0?

**Comment by suned** [comment]
There is no hard line in the sand at the moment, but maybe it would be good to draw one 😄 

Preferably I would like to delay releasing 1.0 until breaking API changes are pretty rare, which hasn't exactly been the case for the past few releases.

I'm currently working on a feature to enable "local" dependency injection akin to what is possible with the "provide" method in ZIO. I expect this to be a breaking change. But after that I don't have new features planned that would obviously require major changes to the API.

There are a number of outstanding issues with the mypy plugin, some of which can maybe be fixed with some of the new/upcoming additions to the typing module such as "ParamSpec" and "TypeVarTuple". I dont have a good overview of when/if this would require changes to the API.

Of the top of my mind, that would be the two main blockers for a 1.0

**Comment by suned** [comment]
I've added a milestone for 1.0.0 and added issues that off the top of my mind present blockers to 1.0.0

I probably can't promise that other issues wont be added along the way, but that should at least give some indication of what I think is needed, and what the progress is towards getting there.
